steps:
  # init_deployment_config.py leaves the validated config.json file in workspace/config so it's available for other build steps
  - name: gcr.io/kittycorn-public/deploy-kittycorn:v2.0
    entrypoint: "bash"
    id: 'init_deploy_config'
    waitFor: ['-']
    args:
      - "-c"
      - |-
        set -e
        echo "Initial configuration ${_CONFIG_FILE}:"
        cat ${_CONFIG_FILE}

        python3 src/common/init_deployment_config.py --config-file "${_CONFIG_FILE}" \
              --sub-validator "src/ORACLE/src"

        echo "Processed configuration:"
        cat ${_CONFIG_FILE}
        echo -e "\n--------------------------------"

  - name: gcr.io/kittycorn-public/deploy-kittycorn:v2.0
    id: 'oracle-deploy'
    waitFor: ['init_deploy_config']
    entrypoint: "bash"
    args:
      - "-c"
      - |-
        
        cp -f "${_CONFIG_FILE}" src/ORACLE/config/config.json
        gcloud builds submit ./src/ORACLE \
          --config=./src/ORACLE/cloudbuild.oracle.yaml \
          --substitutions=_GCS_BUCKET="${_GCS_BUCKET}"

logsBucket: "gs://$_GCS_BUCKET"
timeout: 32400s
substitutions:
  _CONFIG_FILE: "config/config.json"
options:
  substitution_option: "ALLOW_LOOSE"
tags: ["cortex"]