[
    'OracleEbs-GL_BALANCES',
    'OracleEbs-GL_LEDGERS', `OracleEbs-GL_JE_HEADERS`,
    `OracleEbs-GL_JE_LINES`, `OracleEbs-GL_JE_BATCHES`,
    `OracleEbs-GL_JE_CATEGORIES_TL`, `OracleEbs-GL_JE_SOURCES_TL`,
    `OracleEbs-GL_IMPORT_REFERENCES`, `OracleEbs-XLA_AE_LINES`,
    `OracleEbs-XLA_AE_HEADERS`, `OracleEbs-XLA_EVENTS`,
    `OracleEbs-XLA_TRANSACTION_ENTITIES`,
    `OracleEbs-XLA_EVENT_TYPES_TL`,
    `OracleEbs-XLA_EVENT_CLASSES_TL`, `OracleEbs-XLA_DISTRIBUTION_LINKS`,
    `OracleEbs-RA_CUSTOMER_TRX_ALL`,
    `OracleEbs-RA_CUSTOMER_TRX_LINES_ALL`,
    `OracleEbs-RA_CUST_TRX_LINE_GL_DIST_ALL`,
    `OracleEbs-RA_CUST_TRX_TYPES_ALL`,
    `OracleEbs-FA_BOOK_CONTROLS`, `OracleEbs-FA_CATEGORIES_B`,
    `OracleEbs-FA_LOCATIONS`, `OracleEbs-FA_DEPRN_PERIODS`,
    `OracleEbs-FA_BOOKS`, `OracleEbs-FA_ADDITIONS_B`,
    `OracleEbs-FA_ADDITIONS_TL`, `OracleEbs-FA_METHODS`,
    `OracleEbs-FA_ASSET_INVOICES`, `OracleEbs-AP_INVOICES_ALL`,
    `OracleEbs-FA_DISTRIBUTION_HISTORY`,
    `OracleEbs-FA_RETIREMENTS`, `OracleEbs-FA_DEPRN_SUMMARY`,
    `OracleEbs-FND_FLEX_VALUE_SETS`, `OracleEbs-FND_TERRITORIES_TL`,
    `OracleEbs-AP_INVOICE_PAYMENTS_ALL`, `OracleEbs-AP_CHECKS_ALL`, `OracleEbs-AP_PAYMENT_SCHEDULES_ALL`,
    `OracleEbs-IBY_PAYMENT_METHODS_TL`, `OracleEbs-AR_CASH_RECEIPTS_ALL`, `OracleEbs-AR_RECEIVABLE_APPLICATIONS_ALL`,
    `OracleEbs-GL_PERIODS`, `OracleEbs-RA_BATCH_SOURCES_ALL`,
    `OracleEbs-HZ_CUST_ACCOUNTS`, `OracleEbs-HZ_PARTIES`,
    'OracleEbs-PO_HEADERS_ALL',
    'OracleEbs-PO_LINES_ALL',
    'OracleEbs-PO_LINE_LOCATIONS_ALL',
    'OracleEbs-PO_DISTRIBUTIONS_ALL',
    'OracleEbs-AP_HOLDS_ALL',
    'OracleEbs-AP_INVOICE_LINES_ALL',
    'OracleEbs-AP_INVOICE_DISTRIBUTIONS_ALL',
    'OracleEbs-AP_TERMS',
    'OracleEbs-AP_SUPPLIER_SITES_ALL',
    'OracleEbs-DEPARTMENT_LEADER',
    'OracleEbs-PO_REQUISITION_HEADERS_ALL',
    'OracleEbs-PO_REQUISITION_LINES_ALL',
    'OracleEbs-PO_REQ_DISTRIBUTIONS_ALL',
    'OracleEbs-AP_SUPPLIERS',
    'OracleEbs-HR_ALL_ORGANIZATION_UNITS',
    'OracleEbs-HR_LOCATIONS_ALL',
    'OracleEbs-FND_USER',
    'OracleEbs-AP_TERMS_TL',
    'OracleEbs-AP_TOLERANCE_TEMPLATES',
    'OracleEbs-FND_LOOKUP_VALUES',
    'OracleEbs-GL_CODE_COMBINATIONS',
    'OracleEbs-FND_FLEX_VALUES'
]
.forEach(source => declare({
    schema: "Ods",
    name: source
}));