oracle_tables:
  - base_table: AP_HOLD_CODES
  - base_table: AP_PAYMENT_SCHEDULES_ALL
  - base_table: AP_TERMS_LINES

edw_oracle_tables:
  - base_table: Accounting_GLJournalDetails
  - base_table: Accounting_APInvoiceDistributions